---
#
# Ansible managed
#
repository:
  description: Install and configure zabbix_server on your system.
  homepage: https://buluma.github.io/
  topics: zabbix, server, ansible, molecule, tox, playbook, hacktoberfest
